// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7MkHSE-sT2RUPZeyvgePKvJbC6fMTDc8',
    appId: '1:251845818002:web:9bbcd252da7a0cb794584b',
    messagingSenderId: '251845818002',
    projectId: 'armoire-flutter',
    authDomain: 'armoire-flutter.firebaseapp.com',
    storageBucket: 'armoire-flutter.appspot.com',
    measurementId: 'G-KZT27BHPMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmkHeiO6flHPOd56OHr2CZ0ztPlyzgIo',
    appId: '1:251845818002:android:890553a3075e7dcd94584b',
    messagingSenderId: '251845818002',
    projectId: 'armoire-flutter',
    storageBucket: 'armoire-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4uoQ4zkKJdrlD_DFKUoSkrm966yl9KZ8',
    appId: '1:251845818002:ios:0a495090e943f35594584b',
    messagingSenderId: '251845818002',
    projectId: 'armoire-flutter',
    storageBucket: 'armoire-flutter.appspot.com',
    iosClientId: '251845818002-2370dpotehvp8q58achd7rrik4ikiliu.apps.googleusercontent.com',
    iosBundleId: 'com.example.arm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4uoQ4zkKJdrlD_DFKUoSkrm966yl9KZ8',
    appId: '1:251845818002:ios:86a79c1728c7f09d94584b',
    messagingSenderId: '251845818002',
    projectId: 'armoire-flutter',
    storageBucket: 'armoire-flutter.appspot.com',
    iosClientId: '251845818002-he3ra020re141v8k20gmce024h9ua1l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.arm.RunnerTests',
  );
}
